### ISSUE TITLE
LeftButton only if Online

### ISSUE THREAD

**Issue by Crumdidlyumshis** [crumdidlyumshis/BNetToast#3]
@Bunny67 

https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/BNet.lua#L311

Trying to figure this out.

If friend logs on, left click is true. If friend logs off, left click is false.

Why whisper someone when they are offline? :P

**Comment by Bunny67** [comment]
https://github.com/crumdidlyumshis/BNetToast/pull/6/commits/5d7e3cae1cbc910f50fb8136692c25d1bbc6cf1e ?

**Comment by Crumdidlyumshis** [comment]
Thank you!
