### ISSUE TITLE
Guild DropDown

### ISSUE THREAD

**Issue by Crumdidlyumshis** [crumdidlyumshis/BNetToast#7]
@Bunny67 

How would I go about adding the same functionality to the guild members who log in?

FriendsFrame_ShowDropdown for guild members.

**Comment by Bunny67** [comment]
local name, level, class, area, connected = GetFriendInfo(givenName);
        if(name) then
            PlaySound("igMainMenuOptionCheckBoxOn");
            FriendsFrame_ShowDropdown(name, connected, nil, nil, nil, 1);
        else
            FriendsFrame_ShowDropdown(givenName, 1);
        end

**Comment by Crumdidlyumshis** [comment]
It was that simple, dang xD Well thank you!
